version: '3.1'
networks:
    app-tier:
        driver: bridge
services:
    app:
        networks:
            - app-tier
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        container_name: kiwi-backend
        restart: always
        ports:
            - '4000:4000'

    nginx:
        networks:
            - app-tier
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        container_name: kiwi-frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
            - ../certbot/conf:/etc/letsencrypt
            - ../certbot/www:/var/www/certbot
        links:
            - app
        depends_on:
            - app
        restart: always
        ports:
            - '80:80'
            - '443:443'
        expose:
            - '80'
            - '443'
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot:
        image: certbot/certbot
        container_name: certbot_service
        volumes:
            - ../certbot/conf:/etc/letsencrypt
            - ../certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    redis:
        networks:
            - app-tier
        env_file: ./backend/.env
        image: redis:alpine
        container_name: kiwi-redis
        hostname: kiwi
        #network_mode: host
        command: redis-server --requirepass ${REDIS_PASS} --port 6379
        restart: always
        ports:
            - '6379:6379'
